# 데이터셋 설정
dataset:
  path: "C:/Users/sega0/Desktop/grown/cls_yolo11/dataset"
  imgsz: 224

# 모델 설정
model:
  name: "yolo11n-cls.pt"  # yolo11s-cls.pt, yolo11m-cls.pt 등으로 변경 가능

# 학습 설정
training:
  epochs: 50
  batch: 32
  workers: 8
  device: 0  # 0: GPU, cpu: CPU
  seed: 42
  cache: true
  augment: false
  verbose: true

# 실험 설정
experiment:
  base_name: "test"
  project_dir: "runs/classify"
